fixtures:
  repositories:
    wget: https://github.com/maestrodev/puppet-wget.git
    postgres: https://github.com/maestrodev/puppet-postgres.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    maestro: "#{source_dir}"
